databases:
  - name: algorithmmaster-db
    plan: free
    databaseName: algorithmmaster
    user: algorithmmaster

services:
  - type: web
    name: algorithmmaster
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn algorithm_site.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: algorithmmaster-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: RENDER
        value: "1"
