"""Расширение ОАИП модулей 31-45 до 5+ уроков по 40+ мин с 5 темами каждый."""
from django.core.management.base import BaseCommand
from works.models import Subject, TheoryModule, TheoryLesson

LESSONS = {
    'itertools и functools': [
        {
            'title': 'itertools: бесконечные итераторы и комбинаторика',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. Бесконечные итераторы</h3>'
                '<p><code>count(start, step)</code> — бесконечный счётчик: <code>count(10, 2)</code> → 10, 12, 14, ...'
                'Используется совместно с <code>islice()</code> для ограничения.<br>'
                '<code>cycle(iterable)</code> — бесконечное повторение последовательности.<br>'
                '<code>repeat(obj, n)</code> — повторить объект n раз (или бесконечно).</p>'
                '<h3>2. Фильтрация и накопление</h3>'
                '<p><code>takewhile(pred, it)</code> — брать элементы пока предикат True.<br>'
                '<code>dropwhile(pred, it)</code> — пропускать пока True, затем брать всё.<br>'
                '<code>filterfalse(pred, it)</code> — обратный filter: берёт где pred=False.<br>'
                '<code>accumulate(it, func)</code> — накопление: по умолчанию сумма (running total).</p>'
                '<h3>3. Группировка и разбиение</h3>'
                '<p><code>groupby(it, key)</code> — группировать СОСЕДНИЕ элементы по ключу. '
                'Данные должны быть предварительно отсортированы!<br>'
                '<code>islice(it, start, stop, step)</code> — срез итератора без материализации в памяти.<br>'
                '<code>chain(*iterables)</code> — объединить несколько итерируемых в одну цепочку.<br>'
                '<code>chain.from_iterable(it)</code> — аналог, принимает один итерируемый итерируемых.</p>'
                '<h3>4. Комбинаторные итераторы</h3>'
                '<p><code>product(*its, repeat=1)</code> — декартово произведение (вложенные for).<br>'
                '<code>permutations(it, r)</code> — перестановки длины r без повторений.<br>'
                '<code>combinations(it, r)</code> — сочетания длины r (порядок не важен).<br>'
                '<code>combinations_with_replacement(it, r)</code> — сочетания с повторениями.<br>'
                'Все возвращают итераторы — не создают всё в памяти сразу.</p>'
                '<h3>5. Практические паттерны</h3>'
                '<p>Скользящее окно через <code>zip</code> + <code>islice</code>. '
                'Flatten вложенного списка через <code>chain.from_iterable</code>. '
                'Группировка слов по первой букве через <code>groupby(sorted(words), key=str[0])</code>. '
                'Roundrobin планировщик через <code>cycle</code> + <code>islice</code>. '
                'Подсчёт накопленной суммы продаж через <code>accumulate</code>.</p>'
            ),
            'code_example': (
                'import itertools\n\n'
                '# 1. Бесконечный счётчик + ограничение\n'
                'evens = itertools.islice(itertools.count(0, 2), 10)\n'
                'print(list(evens))  # [0, 2, 4, ..., 18]\n\n'
                '# 2. accumulate — накопленная сумма\n'
                'sales = [100, 250, 80, 320, 150]\n'
                'running = list(itertools.accumulate(sales))\n'
                'print(running)  # [100, 350, 430, 750, 900]\n\n'
                '# 3. groupby — группировка по отделу\n'
                'employees = sorted([\n'
                '    ("Alice", "IT"), ("Bob", "HR"),\n'
                '    ("Carol", "IT"), ("Dave", "HR"),\n'
                '], key=lambda x: x[1])\n'
                'for dept, group in itertools.groupby(employees, key=lambda x: x[1]):\n'
                '    print(dept, [e[0] for e in group])\n\n'
                '# 4. combinations — пары игроков\n'
                'players = ["Alice", "Bob", "Carol", "Dave"]\n'
                'matches = list(itertools.combinations(players, 2))\n'
                'print(f"{len(matches)} матчей")\n\n'
                '# 5. Flatten через chain.from_iterable\n'
                'nested = [[1, 2], [3, 4], [5, 6]]\n'
                'flat = list(itertools.chain.from_iterable(nested))\n'
                'print(flat)  # [1, 2, 3, 4, 5, 6]\n\n'
                '# 6. Скользящее окно (window)\n'
                'def sliding_window(seq, n):\n'
                '    iters = itertools.tee(seq, n)\n'
                '    for i, it in enumerate(iters):\n'
                '        next(itertools.islice(it, i, i), None)\n'
                '    return zip(*iters)\n'
                'print(list(sliding_window([1,2,3,4,5], 3)))'
            ),
        },
        {
            'title': 'functools: высокоуровневые функции и кэширование',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. partial — частичное применение функций</h3>'
                '<p><code>functools.partial(func, *args, **kwargs)</code> создаёт новую функцию '
                'с предзаполненными аргументами. Это мощный инструмент для создания специализированных '
                'версий общих функций: <code>double = partial(pow, exp=2)</code>, '
                '<code>log10 = partial(math.log, base=10)</code>.</p>'
                '<h3>2. lru_cache — мемоизация результатов</h3>'
                '<p><code>@lru_cache(maxsize=128)</code> кэширует результаты вызовов функции '
                'по аргументам. LRU (Least Recently Used) — при переполнении вытесняет давно неиспользованные. '
                '<code>maxsize=None</code> или <code>@cache</code> (Python 3.9+) — неограниченный кэш. '
                'Кэш работает только если аргументы хэшируемые (числа, строки, кортежи).</p>'
                '<h3>3. reduce — свёртка последовательности</h3>'
                '<p><code>functools.reduce(func, iterable, initializer)</code> применяет бинарную функцию '
                'слева направо, накапливая результат. Примеры: произведение всех чисел, '
                'глубокое слияние словарей, вычисление факториала. '
                'В Python 3 перенесён в functools (в Python 2 был встроенным).</p>'
                '<h3>4. wraps и update_wrapper — корректные декораторы</h3>'
                '<p><code>@functools.wraps(func)</code> копирует метаданные обёрнутой функции '
                '(__name__, __doc__, __module__, __qualname__, __annotations__). '
                'Без wraps декоратор «ломает» help() и inspect. '
                'Всегда применяй @wraps в своих декораторах.</p>'
                '<h3>5. total_ordering и cmp_to_key</h3>'
                '<p><code>@total_ordering</code> — класс определяет <code>__eq__</code> и одно из '
                '__lt__, __le__, __gt__, __ge__ — остальные выводятся автоматически. '
                '<code>cmp_to_key(func)</code> — преобразует старую cmp-функцию (возвращает -1/0/1) '
                'в key-функцию для sorted(). Полезно при портировании кода Python 2.</p>'
            ),
            'code_example': (
                'import functools, math\n\n'
                '# 1. partial\n'
                'power_of_2 = functools.partial(pow, 2)\n'
                'print([power_of_2(n) for n in range(10)])  # 1,2,4,8,...\n\n'
                '# 2. lru_cache — фибоначчи без экспоненциальных вызовов\n'
                '@functools.lru_cache(maxsize=None)\n'
                'def fib(n):\n'
                '    return n if n < 2 else fib(n-1) + fib(n-2)\n'
                'print(fib(100))       # мгновенно\n'
                'print(fib.cache_info())  # CacheInfo(hits=98, misses=101, ...)\n\n'
                '# 3. reduce — произведение\n'
                'nums = [1, 2, 3, 4, 5]\n'
                'product = functools.reduce(lambda a, b: a * b, nums)\n'
                'print(product)  # 120\n\n'
                '# 4. wraps — корректный декоратор\n'
                'def timer(func):\n'
                '    @functools.wraps(func)  # сохраняет __name__, __doc__\n'
                '    def wrapper(*args, **kwargs):\n'
                '        import time\n'
                '        t0 = time.perf_counter()\n'
                '        result = func(*args, **kwargs)\n'
                '        print(f"{func.__name__}: {time.perf_counter()-t0:.4f}s")\n'
                '        return result\n'
                '    return wrapper\n\n'
                '# 5. total_ordering\n'
                '@functools.total_ordering\n'
                'class Version:\n'
                '    def __init__(self, major, minor):\n'
                '        self.major, self.minor = major, minor\n'
                '    def __eq__(self, other):\n'
                '        return (self.major, self.minor) == (other.major, other.minor)\n'
                '    def __lt__(self, other):\n'
                '        return (self.major, self.minor) < (other.major, other.minor)\n'
                'vs = [Version(2,0), Version(1,9), Version(2,1)]\n'
                'print(sorted(vs, key=lambda v: (v.major, v.minor)))'
            ),
        },
    ],

    'threading и multiprocessing': [
        {
            'title': 'threading: синхронизация и паттерны многопоточности',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. Thread и daemon-потоки</h3>'
                '<p><code>threading.Thread(target=func, args=(), daemon=False)</code>. '
                'Daemon-потоки автоматически завершаются когда умирает главный поток. '
                'Потоки разделяют GIL (Global Interpreter Lock) — только один поток исполняет '
                'байткод Python в момент времени. Это означает: потоки полезны для I/O-операций '
                '(сеть, файлы), но не для CPU-интенсивных вычислений.</p>'
                '<h3>2. Lock и RLock</h3>'
                '<p><code>threading.Lock()</code> — базовый мьютекс: <code>acquire()</code> блокирует '
                'если уже занят. Всегда используй через <code>with lock:</code> чтобы не забыть release(). '
                '<code>RLock</code> (Reentrant Lock) — тот же поток может захватить повторно '
                'без дедлока. Нужен для рекурсивных функций с блокировкой.</p>'
                '<h3>3. Event, Condition, Barrier</h3>'
                '<p><code>threading.Event()</code> — флаг: <code>set()</code> / <code>clear()</code> / <code>wait()</code>. '
                'Один поток сигналит, другие ждут.<br>'
                '<code>Condition</code> — сложная синхронизация с предикатом: '
                '<code>wait_for(predicate)</code> пробуждается только если predicate() == True.<br>'
                '<code>Barrier(n)</code> — n потоков ждут друг друга, затем продолжают вместе.</p>'
                '<h3>4. Queue — потокобезопасный обмен данными</h3>'
                '<p><code>queue.Queue(maxsize=0)</code> — FIFO. '
                '<code>queue.LifoQueue()</code> — стек. '
                '<code>queue.PriorityQueue()</code> — очередь с приоритетом. '
                'Queue.put() блокирует если maxsize достигнут. '
                'Queue.task_done() + Queue.join() — паттерн "подождать обработки всех задач".</p>'
                '<h3>5. ThreadPoolExecutor</h3>'
                '<p><code>concurrent.futures.ThreadPoolExecutor(max_workers=N)</code> — '
                'удобная высокоуровневая обёртка. <code>executor.submit(func, *args)</code> возвращает '
                'Future. <code>executor.map(func, iterable)</code> — параллельный map. '
                '<code>as_completed(futures)</code> — получать результаты по мере готовности. '
                'Автоматически управляет пулом потоков.</p>'
            ),
            'code_example': (
                'import threading, queue, time\n'
                'from concurrent.futures import ThreadPoolExecutor, as_completed\n\n'
                '# 1. Producer-Consumer через Queue\n'
                'tasks = queue.Queue(maxsize=5)\n\n'
                'def producer():\n'
                '    for i in range(10):\n'
                '        tasks.put(f"task_{i}")\n'
                '        print(f"Produced task_{i}")\n'
                '        time.sleep(0.1)\n'
                '    tasks.put(None)  # sentinel\n\n'
                'def consumer():\n'
                '    while True:\n'
                '        item = tasks.get()\n'
                '        if item is None: break\n'
                '        print(f"Processing {item}")\n'
                '        time.sleep(0.3)\n'
                '        tasks.task_done()\n\n'
                '# 2. Event для координации\n'
                'ready = threading.Event()\n\n'
                'def worker(event):\n'
                '    print("Worker waiting...")\n'
                '    event.wait()  # блокируется\n'
                '    print("Worker started!")\n\n'
                '# 3. ThreadPoolExecutor — параллельные запросы\n'
                'def fetch(url):\n'
                '    import urllib.request\n'
                '    with urllib.request.urlopen(url, timeout=5) as r:\n'
                '        return len(r.read())\n\n'
                'urls = ["https://example.com"] * 5\n'
                'with ThreadPoolExecutor(max_workers=5) as ex:\n'
                '    futures = {ex.submit(fetch, url): url for url in urls}\n'
                '    for future in as_completed(futures):\n'
                '        try:\n'
                '            print(f"Size: {future.result()}")\n'
                '        except Exception as e:\n'
                '            print(f"Error: {e}")\n\n'
                '# 4. Lock защита общего ресурса\n'
                'counter = 0\n'
                'lock = threading.Lock()\n\n'
                'def increment():\n'
                '    global counter\n'
                '    for _ in range(10000):\n'
                '        with lock:\n'
                '            counter += 1\n\n'
                'threads = [threading.Thread(target=increment) for _ in range(10)]\n'
                'for t in threads: t.start()\n'
                'for t in threads: t.join()\n'
                'print(counter)  # 100000 (без lock было бы меньше)'
            ),
        },
        {
            'title': 'multiprocessing: обход GIL и параллельные вычисления',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. Process vs Thread — когда что использовать</h3>'
                '<p>multiprocessing создаёт отдельные процессы с собственным интерпретатором — '
                'GIL не мешает. Каждый процесс потребляет 10-30 МБ RAM. '
                'Запуск процесса дороже потока. '
                'Правило: I/O → threading, CPU → multiprocessing.</p>'
                '<h3>2. Pool и ProcessPoolExecutor</h3>'
                '<p><code>multiprocessing.Pool(processes=N)</code> — пул процессов. '
                '<code>pool.map(func, iterable)</code> — параллельный map. '
                '<code>pool.starmap(func, args_list)</code> — несколько аргументов. '
                '<code>pool.imap_unordered(func, it)</code> — результаты по мере готовности, порядок не сохраняется. '
                '<code>ProcessPoolExecutor</code> из concurrent.futures — современный API.</p>'
                '<h3>3. Разделяемая память: Value и Array</h3>'
                '<p><code>multiprocessing.Value("d", 0.0)</code> — одно значение в общей памяти. '
                '<code>multiprocessing.Array("i", [0]*10)</code> — массив. '
                'Доступ через <code>.value</code> или как к списку. '
                'Требуют синхронизации через Lock (встроен): <code>with val.get_lock()</code>.</p>'
                '<h3>4. Queue и Pipe для межпроцессного обмена</h3>'
                '<p><code>multiprocessing.Queue()</code> — потокобезопасная, процессобезопасная очередь. '
                '<code>multiprocessing.Pipe()</code> — двухсторонний канал. '
                'Данные сериализуются через pickle — не все объекты передаются (лямбды не передаются). '
                'Manager().dict() — разделяемый словарь между процессами.</p>'
                '<h3>5. Chunk-обработка больших данных</h3>'
                '<p>Делим большой массив данных на чанки, каждый обрабатывает отдельный процесс. '
                'Оптимальный chunk size: len(data) // num_cpus. '
                'chunksize параметр в pool.map() снижает накладные расходы на IPC. '
                'Паттерн map-reduce: map = параллельная обработка, reduce = агрегация результатов.</p>'
            ),
            'code_example': (
                'import multiprocessing as mp\n'
                'from concurrent.futures import ProcessPoolExecutor\n'
                'import os, time\n\n'
                '# 1. CPU-задача — факторизация числа\n'
                'def is_prime(n):\n'
                '    if n < 2: return False\n'
                '    for i in range(2, int(n**0.5)+1):\n'
                '        if n % i == 0: return False\n'
                '    return True\n\n'
                '# 2. Pool.map — параллельный поиск простых\n'
                'def find_primes(start, end):\n'
                '    return [n for n in range(start, end) if is_prime(n)]\n\n'
                '# 3. ProcessPoolExecutor\n'
                'def parallel_primes(limit=100000):\n'
                '    ncpu = mp.cpu_count()\n'
                '    chunk = limit // ncpu\n'
                '    ranges = [(i*chunk, (i+1)*chunk) for i in range(ncpu)]\n'
                '    with ProcessPoolExecutor(max_workers=ncpu) as ex:\n'
                '        results = ex.map(lambda r: find_primes(*r), ranges)\n'
                '    return [p for primes in results for p in primes]\n\n'
                '# 4. Разделяемый счётчик\n'
                'def worker(shared_val, lock, n):\n'
                '    for _ in range(n):\n'
                '        with lock:\n'
                '            shared_val.value += 1\n\n'
                'if __name__ == "__main__":\n'
                '    val = mp.Value("i", 0)\n'
                '    lock = mp.Lock()\n'
                '    procs = [mp.Process(target=worker, args=(val, lock, 1000))\n'
                '             for _ in range(4)]\n'
                '    for p in procs: p.start()\n'
                '    for p in procs: p.join()\n'
                '    print(val.value)  # 4000\n\n'
                '# 5. Queue producer-consumer\n'
                'def producer(q):\n'
                '    for i in range(20):\n'
                '        q.put(i)\n'
                '    q.put(None)\n\n'
                'def consumer(q):\n'
                '    while (item := q.get()) is not None:\n'
                '        print(f"PID {os.getpid()} got {item}")'
            ),
        },
    ],

    'Type hints и dataclasses': [
        {
            'title': 'Аннотации типов: Union, Optional, Generic',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. Базовые аннотации и typing</h3>'
                '<p>С Python 3.9+ можно писать <code>list[int]</code>, <code>dict[str, int]</code> напрямую. '
                'До 3.9 нужен import из typing: <code>List[int]</code>, <code>Dict[str, int]</code>. '
                '<code>Optional[X]</code> = <code>Union[X, None]</code>. '
                '<code>Union[int, str]</code> (3.10+: <code>int | str</code>). '
                '<code>Any</code> — любой тип, отключает проверку.</p>'
                '<h3>2. Callable, Tuple, TypeVar</h3>'
                '<p><code>Callable[[int, str], bool]</code> — функция с аргументами int, str возвращает bool. '
                '<code>Tuple[int, str, float]</code> — кортеж фиксированной длины. '
                '<code>Tuple[int, ...]</code> — кортеж произвольной длины из int. '
                '<code>TypeVar("T")</code> — обобщённый тип для generic-функций и классов.</p>'
                '<h3>3. Протоколы (Protocol)</h3>'
                '<p><code>typing.Protocol</code> — структурная типизация ("duck typing" для type checker). '
                'Класс соответствует протоколу если имеет нужные методы — без наследования. '
                'Например: <code>Drawable</code> с методом <code>draw()</code> подойдёт любой класс с draw().</p>'
                '<h3>4. TypedDict и NamedTuple</h3>'
                '<p><code>TypedDict</code> — словарь с известными ключами и типами значений. '
                'type checker проверяет обращения. Существует только во время проверки типов — '
                'в runtime это обычный dict. <code>NamedTuple</code> — именованный кортеж с типами, '
                'создаёт класс с слотами, поддерживает значения по умолчанию.</p>'
                '<h3>5. Literal, Final, ClassVar</h3>'
                '<p><code>Literal["GET", "POST"]</code> — переменная может быть только этими значениями. '
                '<code>Final[int]</code> — константа, нельзя переприсвоить. '
                '<code>ClassVar[int]</code> — атрибут класса, не экземпляра. '
                '<code>Annotated[int, Gt(0)]</code> — тип с метаданными (для Pydantic, FastAPI).</p>'
            ),
            'code_example': (
                'from __future__ import annotations\n'
                'from typing import TypeVar, Generic, Protocol, TypedDict\n'
                'from typing import Callable, Literal, Final\n\n'
                '# TypeVar для generic-функции\n'
                'T = TypeVar("T")\n\n'
                'def first(items: list[T]) -> T | None:\n'
                '    return items[0] if items else None\n\n'
                'result: int | None = first([1, 2, 3])  # T = int\n\n'
                '# Protocol — структурная типизация\n'
                'class Drawable(Protocol):\n'
                '    def draw(self) -> None: ...\n\n'
                'class Circle:\n'
                '    def draw(self) -> None: print("Drawing circle")\n\n'
                'class Square:\n'
                '    def draw(self) -> None: print("Drawing square")\n\n'
                'def render(obj: Drawable) -> None:\n'
                '    obj.draw()  # Circle и Square подходят без наследования\n\n'
                '# TypedDict\n'
                'class UserData(TypedDict):\n'
                '    name: str\n'
                '    age: int\n'
                '    email: str | None\n\n'
                'def process_user(u: UserData) -> str:\n'
                '    return f"{u["name"]}, {u["age"]}"\n\n'
                '# Literal\n'
                'HttpMethod = Literal["GET", "POST", "PUT", "DELETE"]\n\n'
                'def request(method: HttpMethod, url: str) -> None:\n'
                '    print(f"{method} {url}")\n\n'
                '# Generic класс\n'
                'class Stack(Generic[T]):\n'
                '    def __init__(self) -> None:\n'
                '        self._items: list[T] = []\n'
                '    def push(self, item: T) -> None:\n'
                '        self._items.append(item)\n'
                '    def pop(self) -> T:\n'
                '        return self._items.pop()\n\n'
                's: Stack[int] = Stack()\n'
                's.push(42)\n'
                'print(s.pop())  # 42'
            ),
        },
        {
            'title': 'dataclasses: автоматическая генерация методов',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. @dataclass и его параметры</h3>'
                '<p><code>@dataclass</code> автоматически генерирует __init__, __repr__, __eq__. '
                'Параметры: <code>order=True</code> — генерирует __lt__, __le__, __gt__, __ge__; '
                '<code>frozen=True</code> — неизменяемый (как NamedTuple, но с методами); '
                '<code>slots=True</code> (Python 3.10+) — использует __slots__ для экономии памяти; '
                '<code>kw_only=True</code> — только keyword аргументы в __init__.</p>'
                '<h3>2. field() — тонкая настройка полей</h3>'
                '<p><code>field(default=None)</code> — значение по умолчанию. '
                '<code>field(default_factory=list)</code> — изменяемые умолчания (ОБЯЗАТЕЛЬНО через factory). '
                '<code>field(repr=False)</code> — исключить из __repr__. '
                '<code>field(compare=False)</code> — исключить из __eq__. '
                '<code>field(init=False)</code> — не в __init__, вычисляется в __post_init__.</p>'
                '<h3>3. __post_init__ и InitVar</h3>'
                '<p><code>__post_init__</code> вызывается после __init__. '
                'Здесь производят вычисления, валидацию, инициализацию полей с <code>init=False</code>. '
                '<code>InitVar[Type]</code> — аргумент только для __init__ и __post_init__, '
                'не становится атрибутом класса. Полезен для пароля, конфигурации.</p>'
                '<h3>4. Наследование dataclasses</h3>'
                '<p>Дочерний класс наследует поля родителя. '
                'Поля без умолчания не могут идти после полей с умолчанием — '
                'поэтому в дочерних классах без умолчаний нужно использовать kw_only=True. '
                'Для сложных иерархий рассмотри pydantic или attrs.</p>'
                '<h3>5. dataclasses.asdict, astuple, replace</h3>'
                '<p><code>dataclasses.asdict(obj)</code> — рекурсивно преобразует в dict (JSON-ready). '
                '<code>dataclasses.astuple(obj)</code> — в кортеж. '
                '<code>dataclasses.replace(obj, field=new_val)</code> — создаёт копию с изменёнными полями. '
                'Полезен для frozen dataclass (нельзя изменить поле напрямую). '
                '<code>dataclasses.fields(cls)</code> — метаданные всех полей.</p>'
            ),
            'code_example': (
                'from dataclasses import dataclass, field, fields, asdict, replace\n'
                'from typing import ClassVar\n\n'
                '@dataclass(order=True, frozen=True)\n'
                'class Point:\n'
                '    x: float\n'
                '    y: float\n\n'
                '    def distance(self, other: "Point") -> float:\n'
                '        return ((self.x-other.x)**2 + (self.y-other.y)**2)**0.5\n\n'
                '@dataclass\n'
                'class Inventory:\n'
                '    name: str\n'
                '    items: list[str] = field(default_factory=list)  # ПРАВИЛЬНО\n'
                '    _count: int = field(default=0, init=False, repr=False)\n'
                '    MAX_SIZE: ClassVar[int] = 100\n\n'
                '    def __post_init__(self):\n'
                '        self._count = len(self.items)\n\n'
                '    def add(self, item: str) -> None:\n'
                '        if self._count >= self.MAX_SIZE:\n'
                '            raise ValueError("Inventory full")\n'
                '        self.items.append(item)\n'
                '        self._count += 1\n\n'
                '# replace для frozen\n'
                'p1 = Point(1.0, 2.0)\n'
                'p2 = replace(p1, x=5.0)  # новый объект\n'
                'print(p1, p2)\n\n'
                '# asdict для JSON\n'
                'inv = Inventory("Weapons", ["sword", "shield"])\n'
                'import json\n'
                'print(json.dumps(asdict(inv), indent=2))\n\n'
                '# Метаданные полей\n'
                'for f in fields(Point):\n'
                '    print(f.name, f.type)'
            ),
        },
        {
            'title': 'Pydantic и валидация данных',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. BaseModel — автовалидация через аннотации</h3>'
                '<p>Pydantic автоматически валидирует и конвертирует данные при создании объекта. '
                '"42" → 42 если поле int. None → Field.default если Optional. '
                'При ошибке: <code>ValidationError</code> с подробным описанием каждого поля. '
                'Используется в FastAPI, Django Ninja, Haystack и других фреймворках.</p>'
                '<h3>2. Field и валидаторы</h3>'
                '<p><code>Field(gt=0, le=100)</code> — числовые ограничения (gt/ge/lt/le). '
                '<code>Field(min_length=3, max_length=50, pattern=r"^[A-Za-z]+$")</code> — строки. '
                '<code>@field_validator("name")</code> — кастомный валидатор поля. '
                '<code>@model_validator(mode="after")</code> — валидация модели целиком (cross-field).</p>'
                '<h3>3. Вложенные модели и списки</h3>'
                '<p>Pydantic рекурсивно валидирует вложенные модели. '
                'Словари автоматически преобразуются в объекты. '
                'Списки валидируются поэлементно. '
                'model.model_dump() → dict, model.model_dump_json() → JSON строка. '
                'Model.model_validate(dict) — создать из словаря.</p>'
                '<h3>4. Settings и конфигурация</h3>'
                '<p>pydantic-settings: <code>BaseSettings</code> читает переменные окружения. '
                'Автоматически: DATABASE_URL из .env файла → <code>settings.database_url</code>. '
                'Поддерживает .env файлы, вложенные настройки, секреты. '
                'Незаменим для конфигурации приложений.</p>'
                '<h3>5. Discriminated Union и Generic модели</h3>'
                '<p><code>Annotated[Cat | Dog, Field(discriminator="type")]</code> — '
                'автоматически выбирает нужный тип по полю. '
                'Generic BaseModel для переиспользуемых обёрток ответа API: '
                '<code>Response[T]</code> с полями <code>data: T</code>, <code>error: str | None</code>.</p>'
            ),
            'code_example': (
                'from pydantic import BaseModel, Field, field_validator, model_validator\n'
                'from typing import Annotated\n'
                'from datetime import date\n\n'
                'class Address(BaseModel):\n'
                '    city: str\n'
                '    country: str = "RU"\n'
                '    zip_code: str = Field(pattern=r"^\\d{6}$")\n\n'
                'class User(BaseModel):\n'
                '    name: str = Field(min_length=2, max_length=50)\n'
                '    age: int = Field(ge=0, le=150)\n'
                '    email: str\n'
                '    address: Address\n'
                '    tags: list[str] = []\n\n'
                '    @field_validator("email")\n'
                '    @classmethod\n'
                '    def validate_email(cls, v: str) -> str:\n'
                '        if "@" not in v:\n'
                '            raise ValueError("Invalid email")\n'
                '        return v.lower()\n\n'
                '    @model_validator(mode="after")\n'
                '    def check_adult_email(self) -> "User":\n'
                '        if self.age < 18 and "kids" not in self.email:\n'
                '            pass  # просто пример\n'
                '        return self\n\n'
                '# Автоконвертация типов\n'
                'user = User(\n'
                '    name="Alice",\n'
                '    age="25",          # str -> int автоматически!\n'
                '    email="ALICE@Example.COM",\n'
                '    address={"city": "Moscow", "zip_code": "101000"},\n'
                ')\n'
                'print(user.age)    # 25 (int)\n'
                'print(user.email)  # alice@example.com\n\n'
                '# Сериализация\n'
                'print(user.model_dump())\n'
                'print(user.model_dump_json(indent=2))'
            ),
        },
    ],

    'Контекстные менеджеры': [
        {
            'title': 'Протокол контекстного менеджера: __enter__ и __exit__',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. Принцип работы with-оператора</h3>'
                '<p><code>with expr as var</code>: Python вызывает <code>expr.__enter__()</code>, '
                'результат присваивается var. При выходе из блока (нормально или через исключение) '
                'вызывается <code>expr.__exit__(exc_type, exc_val, exc_tb)</code>. '
                'Если __exit__ возвращает True — исключение подавляется. '
                'Если False или None — исключение распространяется дальше.</p>'
                '<h3>2. Реализация __enter__ и __exit__</h3>'
                '<p>Класс должен реализовать оба метода. Типичный паттерн: __enter__ возвращает self '
                'или управляемый ресурс. __exit__ освобождает ресурс, логирует ошибку. '
                'Параметры __exit__: exc_type (тип исключения или None), exc_val (значение), '
                'exc_tb (traceback). Для подавления конкретного исключения: '
                '<code>return isinstance(exc_val, SomeError)</code>.</p>'
                '<h3>3. contextlib.contextmanager</h3>'
                '<p>Превращает генератор в контекстный менеджер. '
                'Код до yield — это __enter__. yield — это возвращаемое значение. '
                'Код после yield — это __exit__. '
                'try/finally вокруг yield — гарантирует выполнение очистки. '
                'try/except вокруг yield — обработка исключений из блока with.</p>'
                '<h3>4. contextlib.suppress, closing, nullcontext</h3>'
                '<p><code>contextlib.suppress(ExcType1, ExcType2)</code> — подавляет указанные исключения. '
                'Замена try/except/pass. <code>contextlib.closing(obj)</code> — вызывает obj.close() при выходе. '
                '<code>contextlib.nullcontext(value)</code> — ничего не делает, просто возвращает value. '
                'Полезен для опциональных контекстных менеджеров.</p>'
                '<h3>5. Стекирование и ExitStack</h3>'
                '<p><code>with A() as a, B() as b:</code> — эквивалентно вложенным with. '
                '<code>contextlib.ExitStack()</code> — динамический стек менеджеров. '
                'Позволяет входить в произвольное число менеджеров в цикле. '
                '<code>stack.enter_context(cm)</code> — добавить менеджер. '
                '<code>stack.callback(func)</code> — зарегистрировать функцию очистки.</p>'
            ),
            'code_example': (
                'from contextlib import contextmanager, suppress, ExitStack\n'
                'import time, logging\n\n'
                '# 1. Класс-контекстный менеджер\n'
                'class Timer:\n'
                '    def __init__(self, name: str):\n'
                '        self.name = name\n'
                '    def __enter__(self):\n'
                '        self.start = time.perf_counter()\n'
                '        return self\n'
                '    def __exit__(self, exc_type, exc_val, exc_tb):\n'
                '        elapsed = time.perf_counter() - self.start\n'
                '        print(f"{self.name}: {elapsed:.4f}s")\n'
                '        return False  # не подавляем исключения\n\n'
                'with Timer("Sorting") as t:\n'
                '    sorted(range(100000))\n\n'
                '# 2. @contextmanager — транзакция БД\n'
                '@contextmanager\n'
                'def db_transaction(conn):\n'
                '    try:\n'
                '        yield conn\n'
                '        conn.commit()\n'
                '    except Exception:\n'
                '        conn.rollback()\n'
                '        raise\n\n'
                '# 3. suppress\n'
                'with suppress(FileNotFoundError):\n'
                '    open("nonexistent.txt")  # исключение подавится\n\n'
                '# 4. ExitStack — открыть много файлов\n'
                'filenames = ["a.txt", "b.txt", "c.txt"]\n'
                'with ExitStack() as stack:\n'
                '    files = [stack.enter_context(open(f, "w"))\n'
                '             for f in filenames]\n'
                '    for i, f in enumerate(files):\n'
                '        f.write(f"File {i}\\n")\n'
                '# Все файлы закрыты\n\n'
                '# 5. Подавление конкретного исключения\n'
                'class SafeDiv:\n'
                '    def __enter__(self): return self\n'
                '    def __exit__(self, et, ev, tb):\n'
                '        if isinstance(ev, ZeroDivisionError):\n'
                '            print("Division by zero caught")\n'
                '            return True  # подавить\n'
                '        return False\n\n'
                'with SafeDiv():\n'
                '    x = 1 / 0  # поглощается'
            ),
        },
        {
            'title': 'Продвинутые паттерны контекстных менеджеров',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. Реентерабельные контекстные менеджеры</h3>'
                '<p>Реентерабельный менеджер можно безопасно использовать вложенно. '
                'contextlib.redirect_stdout, redirect_stderr — реентерабельны. '
                'Для собственных: сохраняй предыдущее состояние в стеке. '
                'Не реентерабельный Lock нельзя захватить повторно тем же потоком '
                '— используй RLock.</p>'
                '<h3>2. Async контекстные менеджеры</h3>'
                '<p><code>async with</code> — асинхронные менеджеры: '
                '<code>__aenter__</code> и <code>__aexit__</code> — корутины. '
                '<code>@contextlib.asynccontextmanager</code> — декоратор для async-генераторов. '
                'Используется для async DB-сессий, HTTP-клиентов (aiohttp.ClientSession), '
                'async-locks в asyncio.</p>'
                '<h3>3. Контекстные менеджеры для тестирования</h3>'
                '<p><code>unittest.mock.patch()</code> — контекстный менеджер и декоратор. '
                'Временно заменяет объект mock-объектом внутри блока. '
                '<code>pytest.raises(ExcType)</code> — проверяет что исключение поднялось. '
                '<code>pytest.warns(WarningType)</code> — перехватывает предупреждения. '
                '<code>capfd.readouterr()</code> — перехватывает stdout/stderr.</p>'
                '<h3>4. Управление ресурсами в long-running приложениях</h3>'
                '<p>В серверных приложениях: пул соединений БД через контекстный менеджер. '
                'Освобождение Redis-lock при любом завершении. '
                'Временные файлы: <code>tempfile.NamedTemporaryFile()</code> — автоудаление. '
                '<code>tempfile.TemporaryDirectory()</code> — временная директория.</p>'
                '<h3>5. Декорирование методов как контекстных менеджеров</h3>'
                '<p>Паттерн: класс реализует <code>__enter__/</code><code>__exit__</code>, '
                'а метод возвращает self. Позволяет использовать один объект в двух ролях: '
                'обычный объект и контекстный менеджер. '
                'Пример: объект соединения с БД: <code>conn = DB.connect()</code> '
                'и <code>with DB.connect() as conn</code>.</p>'
            ),
            'code_example': (
                'import contextlib, tempfile, os\n'
                'from unittest.mock import patch\n\n'
                '# 1. Async контекстный менеджер\n'
                'import asyncio\n\n'
                'class AsyncDB:\n'
                '    async def __aenter__(self):\n'
                '        print("Opening async connection")\n'
                '        return self\n'
                '    async def __aexit__(self, *args):\n'
                '        print("Closing async connection")\n'
                '    async def query(self, sql): return []\n\n'
                'async def main():\n'
                '    async with AsyncDB() as db:\n'
                '        result = await db.query("SELECT 1")\n\n'
                '# 2. @asynccontextmanager\n'
                '@contextlib.asynccontextmanager\n'
                'async def managed_resource():\n'
                '    resource = await asyncio.sleep(0)  # симуляция init\n'
                '    try:\n'
                '        yield "resource"\n'
                '    finally:\n'
                '        print("Cleanup")\n\n'
                '# 3. redirect_stdout\n'
                'import io\n'
                'buf = io.StringIO()\n'
                'with contextlib.redirect_stdout(buf):\n'
                '    print("This goes to buf")\n'
                'captured = buf.getvalue()\n\n'
                '# 4. Временный файл\n'
                'with tempfile.NamedTemporaryFile(mode="w", suffix=".txt",\n'
                '                                delete=False) as tmp:\n'
                '    tmp.write("temp data")\n'
                '    tmpname = tmp.name\n'
                'try:\n'
                '    with open(tmpname) as f:\n'
                '        print(f.read())\n'
                'finally:\n'
                '    os.unlink(tmpname)\n\n'
                '# 5. patch для тестов\n'
                'def get_user_age():\n'
                '    import datetime\n'
                '    return datetime.date.today().year - 2000\n\n'
                'with patch("datetime.date") as mock_date:\n'
                '    mock_date.today.return_value.year = 2030\n'
                '    print(get_user_age())  # 30'
            ),
        },
        {
            'title': 'Управление ресурсами: файлы, сеть, БД',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. Работа с файлами через контекстные менеджеры</h3>'
                '<p><code>open()</code> — стандартный контекстный менеджер. '
                'Режимы: r/w/a/rb/wb. encoding="utf-8" обязателен для текстовых файлов. '
                'newline="" важен для CSV. '
                'Для атомарной записи: пишем во временный файл, затем переименовываем. '
                '<code>pathlib.Path.open()</code> — то же, но через Path-объект.</p>'
                '<h3>2. Соединения с БД</h3>'
                '<p>sqlite3.connect() как контекстный менеджер: автокоммит или роллбэк. '
                'Важно: <code>with sqlite3.connect(...) as conn</code> управляет транзакцией, '
                'но НЕ закрывает соединение! Закрывать нужно явно или через closing(). '
                'SQLAlchemy Session: <code>with Session() as session, session.begin()</code>.</p>'
                '<h3>3. Сетевые ресурсы</h3>'
                '<p>urllib.request.urlopen() — контекстный менеджер. '
                'requests.Session() — нужно явно закрывать (не CM сам по себе, но через with). '
                'socket как контекстный менеджер: автоматически закрывает дескриптор. '
                'pathlib в комбинации с сетью: скачать → временный файл → обработать → переместить.</p>'
                '<h3>4. Блокировки файлов и атомарные операции</h3>'
                '<p>Атомарная запись: write to <code>file.tmp</code> → os.replace(tmp, target). '
                'os.replace — атомарна на POSIX. fcntl.flock — блокировка файла (POSIX). '
                'Для кросс-платформенной блокировки: библиотека filelock. '
                'Паттерн «файл-флаг»: создаём файл → работаем → удаляем файл.</p>'
                '<h3>5. Пул соединений как контекстный менеджер</h3>'
                '<p>Пул выдаёт соединение на время работы и возвращает в пул при выходе из with. '
                'contextlib.ExitStack для объединения нескольких ресурсов. '
                'weakref.finalize() — альтернатива __del__ для освобождения ресурсов. '
                'atexit.register() — последний рубеж очистки при выходе из интерпретатора.</p>'
            ),
            'code_example': (
                'import sqlite3, os, pathlib, contextlib\n\n'
                '# 1. Атомарная запись файла\n'
                'def atomic_write(path: str, content: str) -> None:\n'
                '    tmp = path + ".tmp"\n'
                '    try:\n'
                '        with open(tmp, "w", encoding="utf-8") as f:\n'
                '            f.write(content)\n'
                '        os.replace(tmp, path)  # атомарно!\n'
                '    except Exception:\n'
                '        if os.path.exists(tmp):\n'
                '            os.unlink(tmp)\n'
                '        raise\n\n'
                '# 2. SQLite транзакция + закрытие\n'
                '@contextlib.contextmanager\n'
                'def get_db(db_path: str):\n'
                '    conn = sqlite3.connect(db_path)\n'
                '    conn.row_factory = sqlite3.Row\n'
                '    try:\n'
                '        with conn:  # управляет транзакцией\n'
                '            yield conn\n'
                '    finally:\n'
                '        conn.close()  # закрываем явно\n\n'
                'with get_db("test.db") as conn:\n'
                '    conn.execute("CREATE TABLE IF NOT EXISTS t (id INTEGER)")\n'
                '    conn.execute("INSERT INTO t VALUES (42)")\n'
                '# соединение закрыто, транзакция подтверждена\n\n'
                '# 3. Простой пул соединений\n'
                'import queue\n\n'
                'class ConnectionPool:\n'
                '    def __init__(self, dsn: str, size: int = 5):\n'
                '        self._pool: queue.Queue = queue.Queue()\n'
                '        for _ in range(size):\n'
                '            self._pool.put(sqlite3.connect(dsn))\n\n'
                '    @contextlib.contextmanager\n'
                '    def connection(self):\n'
                '        conn = self._pool.get()\n'
                '        try:\n'
                '            yield conn\n'
                '        finally:\n'
                '            self._pool.put(conn)\n\n'
                'pool = ConnectionPool(":memory:")\n'
                'with pool.connection() as conn:\n'
                '    conn.execute("SELECT 1")'
            ),
        },
        {
            'title': 'contextlib: весь арсенал инструментов',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. contextlib.contextmanager подробно</h3>'
                '<p>Генераторная функция с ровно одним yield. '
                'До yield: настройка (приобретение ресурса). '
                'yield value: значение присваивается переменной в "as". '
                'После yield: очистка. try/finally гарантирует очистку даже при исключении. '
                'try/except позволяет обработать исключение и решить — повторно поднять или нет.</p>'
                '<h3>2. contextlib.AbstractContextManager</h3>'
                '<p>Базовый класс. Реализует <code>__enter__</code> (возвращает self) и '
                'абстрактный <code>__exit__</code>. Подход для статической типизации: '
                'наследуй и аннотируй правильно. '
                '<code>AbstractAsyncContextManager</code> — аналог для async.</p>'
                '<h3>3. contextlib.chdir (Python 3.11+)</h3>'
                '<p><code>with contextlib.chdir(path):</code> — временно меняет рабочую директорию. '
                'При выходе возвращает исходную. До 3.11: реализовать самостоятельно через '
                'os.getcwd() / os.chdir(). Полезно в тестах и build-скриптах.</p>'
                '<h3>4. contextlib.aclosing</h3>'
                '<p><code>aclosing(thing)</code> — async-версия closing(). '
                'Гарантирует вызов thing.aclose() при выходе. '
                'Необходим для async-генераторов: если прервать итерацию, '
                'код after yield в генераторе не выполнится без aclosing.</p>'
                '<h3>5. Профессиональные паттерны</h3>'
                '<p>Retry-контекстный менеджер: повторять блок при заданных исключениях. '
                'Span/tracing-менеджер: засекать время + отправлять метрики. '
                'Transaction-менеджер с savepoints для вложенных транзакций. '
                'Dry-run менеджер: подставляет моки в тестовом режиме. '
                'Lock-manager с timeout: <code>Lock.acquire(timeout=5)</code>.</p>'
            ),
            'code_example': (
                'import contextlib, time, logging\n'
                'from typing import Type\n\n'
                '# 1. Retry контекстный менеджер\n'
                '@contextlib.contextmanager\n'
                'def retry(exc_types: tuple, max_attempts: int = 3, delay: float = 1.0):\n'
                '    for attempt in range(max_attempts):\n'
                '        try:\n'
                '            yield attempt\n'
                '            return  # успех — выходим\n'
                '        except exc_types as e:\n'
                '            if attempt == max_attempts - 1:\n'
                '                raise\n'
                '            logging.warning(f"Attempt {attempt+1} failed: {e}")\n'
                '            time.sleep(delay)\n\n'
                'with retry((ConnectionError, TimeoutError), max_attempts=3):\n'
                '    pass  # ваш нестабильный код\n\n'
                '# 2. Span — трассировка производительности\n'
                'class Span:\n'
                '    def __init__(self, name: str):\n'
                '        self.name, self.elapsed = name, 0.0\n'
                '    def __enter__(self):\n'
                '        self._t = time.perf_counter()\n'
                '        return self\n'
                '    def __exit__(self, *args):\n'
                '        self.elapsed = time.perf_counter() - self._t\n'
                '        logging.info(f"[{self.name}] {self.elapsed*1000:.1f}ms")\n\n'
                '# 3. chdir (совместимость)\n'
                '@contextlib.contextmanager\n'
                'def chdir(path):\n'
                '    import os\n'
                '    old = os.getcwd()\n'
                '    os.chdir(path)\n'
                '    try:\n'
                '        yield\n'
                '    finally:\n'
                '        os.chdir(old)\n\n'
                '# 4. nullcontext для опциональных менеджеров\n'
                'def process(data, lock=None):\n'
                '    cm = lock if lock is not None else contextlib.nullcontext()\n'
                '    with cm:\n'
                '        return [x * 2 for x in data]  # thread-safe если lock задан'
            ),
        },
    ],

    'Паттерны проектирования': [
        {
            'title': 'Порождающие паттерны: Factory, Builder, Singleton',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. Factory Method</h3>'
                '<p>Определяет интерфейс создания объекта, но позволяет подклассам решать какой класс создавать. '
                'В Python: фабричная функция или классметод. '
                '<code>Product.from_dict(data)</code>, <code>Connection.create(dialect)</code>. '
                'Преимущество: клиент не знает о конкретных классах, легко расширять.</p>'
                '<h3>2. Abstract Factory</h3>'
                '<p>Семейство связанных объектов без указания конкретных классов. '
                'Пример: UI-фабрика (WindowsFactory, MacFactory) создаёт совместимые Button + Dialog. '
                'В Python: класс с фабричными методами или просто модуль с функциями.</p>'
                '<h3>3. Builder</h3>'
                '<p>Пошаговое создание сложного объекта. Отделяет конструкцию от представления. '
                'Fluent interface (цепочка вызовов): '
                '<code>QueryBuilder().select("*").from_("users").where("age > 18").build()</code>. '
                'В Python часто реализуется через method chaining (return self).</p>'
                '<h3>4. Singleton</h3>'
                '<p>Гарантирует единственный экземпляр класса. '
                'В Python через <code>__new__</code> или модуль (модуль — естественный singleton). '
                'Thread-safe singleton: double-checked locking или through metaclass. '
                'Антипаттерн при тестировании (глобальное состояние). '
                'Альтернатива: dependency injection.</p>'
                '<h3>5. Prototype (прототип)</h3>'
                '<p>Клонирование объектов вместо создания с нуля. '
                '<code>copy.copy()</code> — поверхностная копия. '
                '<code>copy.deepcopy()</code> — глубокая копия. '
                '<code>__copy__</code> / <code>__deepcopy__</code> — кастомное клонирование. '
                'Полезен для шаблонов объектов или дорогостоящих инициализаций.</p>'
            ),
            'code_example': (
                'import copy, threading\n\n'
                '# 1. Factory Method\n'
                'class Notification:\n'
                '    def send(self, msg): raise NotImplementedError\n\n'
                'class EmailNotification(Notification):\n'
                '    def send(self, msg): print(f"Email: {msg}")\n\n'
                'class SMSNotification(Notification):\n'
                '    def send(self, msg): print(f"SMS: {msg}")\n\n'
                'def create_notification(type: str) -> Notification:\n'
                '    types = {"email": EmailNotification, "sms": SMSNotification}\n'
                '    cls = types.get(type)\n'
                '    if not cls: raise ValueError(f"Unknown: {type}")\n'
                '    return cls()\n\n'
                '# 2. Builder — SQL Query\n'
                'class QueryBuilder:\n'
                '    def __init__(self):\n'
                '        self._select = "*"\n'
                '        self._table = ""\n'
                '        self._where = []\n'
                '        self._limit = None\n\n'
                '    def select(self, cols: str) -> "QueryBuilder":\n'
                '        self._select = cols; return self\n'
                '    def from_(self, table: str) -> "QueryBuilder":\n'
                '        self._table = table; return self\n'
                '    def where(self, cond: str) -> "QueryBuilder":\n'
                '        self._where.append(cond); return self\n'
                '    def limit(self, n: int) -> "QueryBuilder":\n'
                '        self._limit = n; return self\n'
                '    def build(self) -> str:\n'
                '        q = f"SELECT {self._select} FROM {self._table}"\n'
                '        if self._where: q += " WHERE " + " AND ".join(self._where)\n'
                '        if self._limit: q += f" LIMIT {self._limit}"\n'
                '        return q\n\n'
                'q = QueryBuilder().select("name, age").from_("users").where("age > 18").limit(10).build()\n'
                'print(q)\n\n'
                '# 3. Thread-safe Singleton\n'
                'class Config:\n'
                '    _instance = None\n'
                '    _lock = threading.Lock()\n\n'
                '    def __new__(cls):\n'
                '        with cls._lock:\n'
                '            if cls._instance is None:\n'
                '                cls._instance = super().__new__(cls)\n'
                '                cls._instance.data = {}\n'
                '        return cls._instance\n\n'
                'cfg1, cfg2 = Config(), Config()\n'
                'print(cfg1 is cfg2)  # True'
            ),
        },
        {
            'title': 'Структурные и поведенческие паттерны',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. Decorator (структурный)</h3>'
                '<p>Добавляет поведение объекту не меняя его класс. '
                'В Python функции-декораторы — это и есть паттерн Decorator. '
                'Классическая реализация: обёртка с тем же интерфейсом. '
                'Примеры: кэширование, логирование, авторизация, retry, circuit breaker.</p>'
                '<h3>2. Observer (наблюдатель)</h3>'
                '<p>Объект (Subject) уведомляет подписчиков об изменениях. '
                'Реализация: список callback-ов или методов. '
                '<code>subject.subscribe(callback)</code> / <code>subject.notify(event)</code>. '
                'В Python: встроенная библиотека <code>weakref</code> для слабых ссылок на наблюдателей. '
                'Паттерн лежит в основе GUI-фреймворков, event-систем, pub/sub.</p>'
                '<h3>3. Strategy</h3>'
                '<p>Семейство алгоритмов, инкапсулированных и взаимозаменяемых. '
                'В Python: передача функции как аргумента. '
                '<code>sorted(data, key=lambda x: x.price)</code> — это Strategy. '
                'Классическая: интерфейс + конкретные классы. '
                'Питоний вариант: просто callable.</p>'
                '<h3>4. Command</h3>'
                '<p>Инкапсулирует запрос как объект. Поддерживает undo/redo. '
                'В Python: объект с методом execute() и undo(). '
                'Список команд = история операций. '
                'Применение: редакторы, транзакции, очереди задач (Celery-задачи — это Command).</p>'
                '<h3>5. Proxy и Facade</h3>'
                '<p>Proxy: объект-посредник с тем же интерфейсом. '
                'Виды: Virtual (ленивая инициализация), Remote (RPC), Protection (авторизация), '
                'Caching (кэширование). '
                'Facade: упрощённый интерфейс к сложной подсистеме. '
                'Пример: класс VideoConverter, скрывающий работу с кодеками, форматами, метаданными.</p>'
            ),
            'code_example': (
                'from typing import Callable, Protocol\n'
                'import weakref\n\n'
                '# 1. Observer\n'
                'class EventEmitter:\n'
                '    def __init__(self):\n'
                '        self._handlers: dict[str, list[Callable]] = {}\n\n'
                '    def on(self, event: str, handler: Callable) -> None:\n'
                '        self._handlers.setdefault(event, []).append(handler)\n\n'
                '    def emit(self, event: str, *args, **kwargs) -> None:\n'
                '        for handler in self._handlers.get(event, []):\n'
                '            handler(*args, **kwargs)\n\n'
                'emitter = EventEmitter()\n'
                'emitter.on("data", lambda d: print(f"Got: {d}"))\n'
                'emitter.on("data", lambda d: print(f"Logged: {d}"))\n'
                'emitter.emit("data", {"value": 42})\n\n'
                '# 2. Strategy\n'
                'from typing import Protocol\n\n'
                'class SortStrategy(Protocol):\n'
                '    def sort(self, data: list) -> list: ...\n\n'
                'def bubble_sort(data: list) -> list:\n'
                '    data = data[:]\n'
                '    for i in range(len(data)):\n'
                '        for j in range(len(data)-i-1):\n'
                '            if data[j] > data[j+1]:\n'
                '                data[j], data[j+1] = data[j+1], data[j]\n'
                '    return data\n\n'
                'class Sorter:\n'
                '    def __init__(self, strategy: Callable = sorted):\n'
                '        self.strategy = strategy\n'
                '    def sort(self, data: list) -> list:\n'
                '        return self.strategy(data)\n\n'
                '# 3. Command с undo\n'
                'class TextEditor:\n'
                '    def __init__(self): self.text = ""; self._history = []\n'
                '    def execute(self, cmd): self._history.append(cmd); cmd.execute(self)\n'
                '    def undo(self):\n'
                '        if self._history: self._history.pop().undo(self)\n\n'
                'class InsertCommand:\n'
                '    def __init__(self, text: str): self.text = text\n'
                '    def execute(self, editor): editor.text += self.text\n'
                '    def undo(self, editor): editor.text = editor.text[:-len(self.text)]\n\n'
                'e = TextEditor()\n'
                'e.execute(InsertCommand("Hello"))\n'
                'e.execute(InsertCommand(" World"))\n'
                'print(e.text)   # Hello World\n'
                'e.undo()\n'
                'print(e.text)   # Hello'
            ),
        },
        {
            'title': 'Паттерны в реальных Python-проектах',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. Repository паттерн</h3>'
                '<p>Изолирует бизнес-логику от хранилища данных. '
                'Интерфейс: get(id), list(filter), save(entity), delete(id). '
                'Реализации: InMemoryRepo (тесты), SQLiteRepo, PostgresRepo. '
                'Код не зависит от конкретной БД — легко мигрировать.</p>'
                '<h3>2. Unit of Work</h3>'
                '<p>Отслеживает все изменения и фиксирует их одной транзакцией. '
                'Предотвращает частичные обновления. '
                'В SQLAlchemy: Session — это Unit of Work. '
                'Работает совместно с Repository: UoW выдаёт репозитории и управляет транзакцией.</p>'
                '<h3>3. Dependency Injection</h3>'
                '<p>Зависимости передаются снаружи, а не создаются внутри. '
                '<code>class Service: def __init__(self, repo: IRepo): self.repo = repo</code>. '
                'Облегчает тестирование (подмена mock). Снижает связанность. '
                'Фреймворки DI: injector, lagom. FastAPI Depends — встроенный DI.</p>'
                '<h3>4. Event Sourcing</h3>'
                '<p>Состояние = последовательность событий. Текущее состояние — результат replay всех событий. '
                'Преимущества: аудит-лог, точка восстановления, возможность replay в другой проекции. '
                'Реализация: список Event-объектов + apply(event) метод на агрегате.</p>'
                '<h3>5. Применение паттернов в Django/FastAPI</h3>'
                '<p>Django ORM: ActiveRecord (модель = данные + логика). '
                'DRF Serializer — это Builder + Strategy. '
                'FastAPI Depends — Dependency Injection. '
                'Celery task — Command паттерн. '
                'Django signals — Observer паттерн. '
                'Middleware — Chain of Responsibility.</p>'
            ),
            'code_example': (
                'from abc import ABC, abstractmethod\n'
                'from typing import Protocol, TypeVar, Generic\n\n'
                'T = TypeVar("T")\n\n'
                '# 1. Repository интерфейс\n'
                'class Repository(Protocol[T]):\n'
                '    def get(self, id: int) -> T | None: ...\n'
                '    def save(self, entity: T) -> None: ...\n'
                '    def delete(self, id: int) -> None: ...\n'
                '    def list(self) -> list[T]: ...\n\n'
                'from dataclasses import dataclass\n\n'
                '@dataclass\n'
                'class User:\n'
                '    id: int\n'
                '    name: str\n'
                '    email: str\n\n'
                '# 2. InMemory реализация для тестов\n'
                'class InMemoryUserRepo:\n'
                '    def __init__(self): self._store: dict[int, User] = {}\n'
                '    def get(self, id: int) -> User | None: return self._store.get(id)\n'
                '    def save(self, u: User) -> None: self._store[u.id] = u\n'
                '    def delete(self, id: int) -> None: self._store.pop(id, None)\n'
                '    def list(self) -> list[User]: return list(self._store.values())\n\n'
                '# 3. Сервис с DI\n'
                'class UserService:\n'
                '    def __init__(self, repo: InMemoryUserRepo):\n'
                '        self._repo = repo\n\n'
                '    def register(self, name: str, email: str) -> User:\n'
                '        id = max((u.id for u in self._repo.list()), default=0) + 1\n'
                '        user = User(id, name, email)\n'
                '        self._repo.save(user)\n'
                '        return user\n\n'
                '    def get_user(self, id: int) -> User | None:\n'
                '        return self._repo.get(id)\n\n'
                '# 4. Использование\n'
                'repo = InMemoryUserRepo()\n'
                'svc = UserService(repo)\n'
                'u = svc.register("Alice", "alice@example.com")\n'
                'print(svc.get_user(u.id))'
            ),
        },
    ],

    'Тестирование с pytest': [
        {
            'title': 'pytest: фикстуры, параметризация и маркировка',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. Фикстуры (fixtures)</h3>'
                '<p>Фикстура — функция с декоратором <code>@pytest.fixture</code>, '
                'подготавливает данные или ресурс для тестов. '
                'pytest автоматически внедряет фикстуры по имени параметра. '
                'Scope: function (по умолчанию, для каждого теста), class, module, session. '
                '<code>yield</code> в фикстуре — всё до yield это setup, после — teardown.</p>'
                '<h3>2. conftest.py</h3>'
                '<p>conftest.py — специальный файл, фикстуры в нём доступны всем тестам в директории. '
                'Несколько conftest.py на разных уровнях — фикстуры наследуются. '
                'Здесь регистрируют хуки pytest, кастомные маркеры, плагины.</p>'
                '<h3>3. Параметризация (@pytest.mark.parametrize)</h3>'
                '<p><code>@pytest.mark.parametrize("input,expected", [(1, 1), (2, 4), (3, 9)])</code>. '
                'Один тест запускается несколько раз с разными данными. '
                'Можно параметризовать фикстуру тоже (params в @fixture). '
                'indirect=True — передать параметр в фикстуру, а не напрямую.</p>'
                '<h3>4. Маркировка и фильтрация</h3>'
                '<p><code>@pytest.mark.slow</code> — кастомный маркер. '
                '<code>pytest -m "not slow"</code> — запустить без медленных. '
                '<code>@pytest.mark.skip(reason="...")</code> — пропустить. '
                '<code>@pytest.mark.xfail(strict=True)</code> — ожидаемое падение. '
                'Маркеры регистрируют в pytest.ini или pyproject.toml.</p>'
                '<h3>5. Плагины: pytest-cov, pytest-mock, pytest-asyncio</h3>'
                '<p>pytest-cov: <code>pytest --cov=mypackage --cov-report=html</code> — покрытие кода. '
                'pytest-mock: фикстура <code>mocker</code> для mock-объектов. '
                'pytest-asyncio: <code>@pytest.mark.asyncio</code> для async-тестов. '
                'pytest-benchmark: измерение производительности в тестах. '
                'pytest-xdist: параллельный запуск тестов.</p>'
            ),
            'code_example': (
                'import pytest\n'
                'from unittest.mock import MagicMock, patch\n\n'
                '# Тестируемый код\n'
                'class UserService:\n'
                '    def __init__(self, db):\n'
                '        self.db = db\n'
                '    def create_user(self, name: str, email: str) -> dict:\n'
                '        if not email or "@" not in email:\n'
                '            raise ValueError("Invalid email")\n'
                '        user = {"id": self.db.next_id(), "name": name, "email": email}\n'
                '        self.db.save(user)\n'
                '        return user\n\n'
                '# conftest.py содержимое\n'
                '@pytest.fixture\n'
                'def mock_db():\n'
                '    db = MagicMock()\n'
                '    db.next_id.return_value = 1\n'
                '    return db\n\n'
                '@pytest.fixture\n'
                'def user_service(mock_db):\n'
                '    return UserService(mock_db)\n\n'
                '# Тесты\n'
                '@pytest.mark.parametrize("name,email", [\n'
                '    ("Alice", "alice@example.com"),\n'
                '    ("Bob", "bob@test.org"),\n'
                '    ("Иван", "ivan@ru.com"),\n'
                '])\n'
                'def test_create_user_success(user_service, mock_db, name, email):\n'
                '    user = user_service.create_user(name, email)\n'
                '    assert user["name"] == name\n'
                '    assert user["email"] == email\n'
                '    mock_db.save.assert_called_once()\n\n'
                '@pytest.mark.parametrize("bad_email", [\n'
                '    "", "notanemail", "no-at-sign", None,\n'
                '])\n'
                'def test_create_user_invalid_email(user_service, bad_email):\n'
                '    with pytest.raises(ValueError, match="Invalid email"):\n'
                '        user_service.create_user("Test", bad_email)\n\n'
                '@pytest.fixture(scope="module")\n'
                'def db_connection():\n'
                '    import sqlite3\n'
                '    conn = sqlite3.connect(":memory:")\n'
                '    conn.execute("CREATE TABLE users (id INT, name TEXT)")\n'
                '    yield conn\n'
                '    conn.close()'
            ),
        },
        {
            'title': 'TDD и стратегии тестирования',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. TDD — Test-Driven Development</h3>'
                '<p>Цикл Red → Green → Refactor. '
                '1. Написать тест (он упадёт — Red). '
                '2. Написать минимальный код чтобы тест прошёл (Green). '
                '3. Улучшить код не меняя тесты (Refactor). '
                'TDD приводит к хорошему дизайну: тестируемый код = слабосвязанный код.</p>'
                '<h3>2. Уровни тестирования</h3>'
                '<p>Unit: изолированный тест одной функции/класса. Mock все зависимости. '
                'Integration: несколько компонентов вместе. Реальная БД. '
                'E2E: весь стек от запроса до ответа. Реальный HTTP. '
                'Правило пирамиды: много unit, меньше integration, мало E2E.</p>'
                '<h3>3. Test Doubles: Mock, Stub, Spy, Fake</h3>'
                '<p>Stub — возвращает заранее заданные данные. '
                'Mock — проверяет что методы вызывались правильно. '
                'Spy — реальный объект + журнал вызовов. '
                'Fake — работающая имплементация (InMemoryDB). '
                'unittest.mock.MagicMock — комбо mock+stub.</p>'
                '<h3>4. Property-based testing (Hypothesis)</h3>'
                '<p>Hypothesis генерирует тысячи случайных входных данных. '
                '<code>@given(st.integers(), st.integers())</code>. '
                'Находит граничные случаи которые мы не придумали. '
                'Стратегии: st.text(), st.lists(), st.dictionaries(), st.from_type(MyClass).</p>'
                '<h3>5. Мутационное тестирование</h3>'
                '<p>Mutmut, Cosmic Ray — вносят мутации в код (== → !=, + → -). '
                'Проверяют что тесты ловят изменения. '
                'Высокое покрытие ≠ хорошие тесты. '
                'Мутационный тест: 100% мутаций пойманы = действительно хорошие тесты.</p>'
            ),
            'code_example': (
                '# TDD пример: реализация стека\n'
                'import pytest\n\n'
                '# Шаг 1: пишем тесты\n'
                'class TestStack:\n'
                '    def test_empty_stack(self):\n'
                '        s = Stack()\n'
                '        assert s.is_empty()\n'
                '        assert len(s) == 0\n\n'
                '    def test_push_and_pop(self):\n'
                '        s = Stack()\n'
                '        s.push(1)\n'
                '        s.push(2)\n'
                '        assert s.pop() == 2\n'
                '        assert s.pop() == 1\n\n'
                '    def test_peek(self):\n'
                '        s = Stack()\n'
                '        s.push(42)\n'
                '        assert s.peek() == 42\n'
                '        assert len(s) == 1  # peek не удаляет\n\n'
                '    def test_pop_empty_raises(self):\n'
                '        s = Stack()\n'
                '        with pytest.raises(IndexError):\n'
                '            s.pop()\n\n'
                '# Шаг 2: реализация\n'
                'class Stack:\n'
                '    def __init__(self): self._items = []\n'
                '    def push(self, item): self._items.append(item)\n'
                '    def pop(self):\n'
                '        if not self._items: raise IndexError("Empty stack")\n'
                '        return self._items.pop()\n'
                '    def peek(self):\n'
                '        if not self._items: raise IndexError("Empty stack")\n'
                '        return self._items[-1]\n'
                '    def is_empty(self): return len(self._items) == 0\n'
                '    def __len__(self): return len(self._items)\n\n'
                '# Hypothesis property-based test\n'
                'from hypothesis import given, strategies as st\n\n'
                '@given(st.lists(st.integers()))\n'
                'def test_stack_preserves_order(items):\n'
                '    s = Stack()\n'
                '    for item in items:\n'
                '        s.push(item)\n'
                '    result = []\n'
                '    while not s.is_empty():\n'
                '        result.append(s.pop())\n'
                '    assert result == list(reversed(items))'
            ),
        },
        {
            'title': 'pytest и базы данных, HTTP, async',
            'estimated_minutes': 40,
            'content': (
                '<h3>1. Тестирование с SQLite/PostgreSQL</h3>'
                '<p>Для unit-тестов: SQLite :memory: — быстро, без setup. '
                'pytest-postgresql, pytest-django — автоматически создают тестовую БД. '
                'factory_boy — генерация тестовых данных (Model Factories). '
                'Faker — реалистичные тестовые данные (имена, email, адреса).</p>'
                '<h3>2. Тестирование HTTP через httpx/requests-mock</h3>'
                '<p>responses (для requests) — перехватывает HTTP-запросы. '
                'httpx.MockTransport — мокирует httpx. '
                'respx — async-мокирование httpx. '
                'responses.add(method, url, json={...}, status=200) — задать ответ. '
                'Проверять что URL был вызван: responses.calls[0].request.url.</p>'
                '<h3>3. FastAPI TestClient</h3>'
                '<p><code>from fastapi.testclient import TestClient; client = TestClient(app)</code>. '
                'Синхронный клиент поверх httpx — не нужен запущенный сервер. '
                'Переопределять зависимости: <code>app.dependency_overrides[get_db] = lambda: mock_db</code>. '
                'Тестировать стримминг, WebSocket, background tasks.</p>'
                '<h3>4. Async тесты с pytest-asyncio</h3>'
                '<p><code>@pytest.mark.asyncio</code> — отмечает async-тест. '
                'asyncio_mode = "auto" в pytest.ini — все async-тесты автоматически. '
                '<code>pytest-anyio</code> — поддерживает trio и asyncio. '
                'Мокирование async-функций: <code>AsyncMock</code> из unittest.mock.</p>'
                '<h3>5. Снэпшот-тестирование (syrupy)</h3>'
                '<p>syrupy — сохраняет первый запуск как "снэпшот". '
                'Последующие запуски сравнивают с сохранённым. '
                'Для сложных структур (JSON-ответы API, HTML-разметка). '
                'assert response.json() == snapshot. Обновление: pytest --snapshot-update.</p>'
            ),
            'code_example': (
                'import pytest\n'
                'from unittest.mock import AsyncMock, patch\n\n'
                '# 1. FastAPI TestClient\n'
                'from fastapi import FastAPI, Depends\n'
                'from fastapi.testclient import TestClient\n\n'
                'app = FastAPI()\n\n'
                'def get_db():\n'
                '    return {"users": []}\n\n'
                '@app.get("/users/{user_id}")\n'
                'def get_user(user_id: int, db=Depends(get_db)):\n'
                '    user = next((u for u in db["users"] if u["id"] == user_id), None)\n'
                '    if not user: return {"error": "not found"}, 404\n'
                '    return user\n\n'
                'def test_get_user_not_found():\n'
                '    client = TestClient(app)\n'
                '    response = client.get("/users/999")\n'
                '    assert response.status_code == 200  # или 404 с правильным обработчиком\n\n'
                '# Dependency override\n'
                'def test_get_existing_user():\n'
                '    fake_db = {"users": [{"id": 1, "name": "Alice"}]}\n'
                '    app.dependency_overrides[get_db] = lambda: fake_db\n'
                '    client = TestClient(app)\n'
                '    response = client.get("/users/1")\n'
                '    assert response.json()["name"] == "Alice"\n'
                '    app.dependency_overrides.clear()\n\n'
                '# 2. Async тест\n'
                'import asyncio\n\n'
                'async def fetch_data(url: str) -> dict:\n'
                '    import aiohttp\n'
                '    async with aiohttp.ClientSession() as s:\n'
                '        async with s.get(url) as r:\n'
                '            return await r.json()\n\n'
                '@pytest.mark.asyncio\n'
                'async def test_fetch_data():\n'
                '    mock_response = AsyncMock()\n'
                '    mock_response.json = AsyncMock(return_value={"key": "value"})\n'
                '    with patch("aiohttp.ClientSession") as MockSession:\n'
                '        MockSession.return_value.__aenter__.return_value.get\\\n'
                '            .return_value.__aenter__.return_value = mock_response\n'
                '        result = await fetch_data("https://api.example.com")\n'
                '        assert result == {"key": "value"}'
            ),
        },
    ],

    'SQLite и работа с базами данных': [
        {
            'title': 'sqlite3: продвинутые возможности',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. Транзакции и изоляция</h3>'
                '<p>sqlite3 по умолчанию в autocommit режиме при DDL, но открывает транзакцию при DML. '
                '<code>isolation_level=None</code> — полный autocommit. '
                '<code>isolation_level="DEFERRED"/"IMMEDIATE"/"EXCLUSIVE"</code> — явные транзакции. '
                'WAL режим: <code>PRAGMA journal_mode=WAL</code> — позволяет параллельные чтения и запись. '
                'Rollback при ошибке: <code>with conn:</code> автоматически commit/rollback.</p>'
                '<h3>2. Кастомные функции и агрегаты</h3>'
                '<p><code>conn.create_function("name", nargs, func)</code> — Python-функция в SQL. '
                '<code>conn.create_aggregate("name", nargs, AggClass)</code> — агрегатная функция. '
                'AggClass должен иметь step(values) и finalize() методы. '
                'Пример: REGEXP-функция, HAVERSINE-расстояние, MEDIAN-агрегат.</p>'
                '<h3>3. Row factory и типизация</h3>'
                '<p><code>conn.row_factory = sqlite3.Row</code> — доступ к столбцам по имени: '
                '<code>row["name"]</code> или <code>row[0]</code>. '
                'Кастомная row_factory: <code>lambda cursor, row: dict(zip([c[0] for c in cursor.description], row))</code>. '
                'detect_types=PARSE_DECLTYPES — автоконвертация типов (date, datetime). '
                '<code>sqlite3.register_adapter</code> и <code>register_converter</code>.</p>'
                '<h3>4. Многопоточность и connection pooling</h3>'
                '<p><code>check_same_thread=False</code> — передать соединение между потоками. '
                'Но SQLite поддерживает WAL для параллельных читателей. '
                'Паттерн: пул через threading.local() — каждый поток своё соединение. '
                'В async: aiosqlite — асинхронная обёртка над sqlite3.</p>'
                '<h3>5. Полнотекстовый поиск (FTS5) и JSON</h3>'
                '<p>FTS5: <code>CREATE VIRTUAL TABLE t USING fts5(content)</code>. '
                '<code>SELECT * FROM t WHERE t MATCH "python AND sqlite"</code>. '
                'Ранжирование по релевантности: <code>ORDER BY rank</code>. '
                'JSON функции (SQLite 3.38+): <code>json_extract</code>, <code>json_each</code>, '
                '<code>json_array</code> — работа с JSON-полями прямо в SQL.</p>'
            ),
            'code_example': (
                'import sqlite3, re\n\n'
                '# 1. WAL + кастомная REGEXP функция\n'
                'conn = sqlite3.connect("demo.db")\n'
                'conn.execute("PRAGMA journal_mode=WAL")\n'
                'conn.row_factory = sqlite3.Row\n\n'
                'def regexp(pattern, value):\n'
                '    if value is None: return False\n'
                '    return bool(re.search(pattern, str(value)))\n'
                'conn.create_function("REGEXP", 2, regexp)\n\n'
                '# 2. Создание таблицы + индексы\n'
                'conn.executescript("""\n'
                '    CREATE TABLE IF NOT EXISTS products (\n'
                '        id      INTEGER PRIMARY KEY,\n'
                '        name    TEXT NOT NULL,\n'
                '        price   REAL NOT NULL,\n'
                '        tags    TEXT  -- JSON array\n'
                '    );\n'
                '    CREATE INDEX IF NOT EXISTS idx_price ON products(price);\n'
                '""")\n\n'
                '# 3. Вставка + транзакция\n'
                'import json\n'
                'products = [\n'
                '    ("Ноутбук", 50000, ["electronics", "computer"]),\n'
                '    ("Телефон", 25000, ["electronics", "mobile"]),\n'
                '    ("Книга Python", 1500, ["books", "programming"]),\n'
                ']\n'
                'with conn:  # auto commit/rollback\n'
                '    conn.executemany(\n'
                '        "INSERT OR IGNORE INTO products(name, price, tags) VALUES (?,?,?)",\n'
                '        [(n, p, json.dumps(t)) for n, p, t in products]\n'
                '    )\n\n'
                '# 4. Кастомный агрегат MEDIAN\n'
                'class Median:\n'
                '    def __init__(self): self.values = []\n'
                '    def step(self, v):\n'
                '        if v is not None: self.values.append(v)\n'
                '    def finalize(self):\n'
                '        if not self.values: return None\n'
                '        s = sorted(self.values); n = len(s)\n'
                '        return s[n//2] if n % 2 else (s[n//2-1]+s[n//2])/2\n\n'
                'conn.create_aggregate("MEDIAN", 1, Median)\n'
                'row = conn.execute("SELECT MEDIAN(price) FROM products").fetchone()\n'
                'print(f"Median price: {row[0]}")'
            ),
        },
        {
            'title': 'Работа с несколькими БД: PostgreSQL, миграции',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. psycopg2 и psycopg3</h3>'
                '<p>psycopg2 — стандарт де-факто для PostgreSQL в Python. '
                'psycopg3 (psycopg) — переработанная версия с async поддержкой. '
                '<code>conn = psycopg2.connect(dsn="postgresql://user:pass@host/db")</code>. '
                'Параметрированные запросы обязательны: <code>cursor.execute("SELECT %s", (value,))</code>. '
                'Никогда не форматируй SQL через f-string — SQL injection!</p>'
                '<h3>2. Connection pooling с psycopg2</h3>'
                '<p>psycopg2.pool.ThreadedConnectionPool(minconn, maxconn, dsn). '
                '50 подключений к БД могут исчерпать ресурсы — нужен пул. '
                'pgBouncer — внешний пул соединений на уровне прокси. '
                'asyncpg — самый быстрый async-драйвер PostgreSQL для Python.</p>'
                '<h3>3. Миграции: Alembic</h3>'
                '<p>Alembic — инструмент миграций для SQLAlchemy. '
                '<code>alembic init alembic</code> — инициализация. '
                '<code>alembic revision --autogenerate -m "add users table"</code>. '
                '<code>alembic upgrade head</code> — применить все миграции. '
                '<code>alembic downgrade -1</code> — откатить одну. '
                'Версии хранятся в БД и файлах migrations/.</p>'
                '<h3>4. Индексы и оптимизация запросов</h3>'
                '<p>EXPLAIN ANALYZE — план выполнения запроса. '
                'Seq Scan vs Index Scan — разница в скорости. '
                'Частичный индекс: <code>CREATE INDEX ON users(email) WHERE active = true</code>. '
                'GIN-индекс для полнотекстового поиска. '
                'JSONB-индекс для JSON-полей.</p>'
                '<h3>5. Хранимые процедуры и триггеры</h3>'
                '<p>PostgreSQL: функции на PL/pgSQL, Python (pl/python), JavaScript. '
                'Триггеры: BEFORE/AFTER INSERT/UPDATE/DELETE. '
                'Применения: аудит-лог, автозаполнение updated_at, денормализация. '
                'Вызов функции из Python: cursor.callproc("my_func", [arg1, arg2]).</p>'
            ),
            'code_example': (
                '# psycopg2 + пул соединений\n'
                'import psycopg2\n'
                'from psycopg2 import pool\n'
                'from contextlib import contextmanager\n\n'
                'class Database:\n'
                '    def __init__(self, dsn: str, minconn=2, maxconn=10):\n'
                '        self._pool = pool.ThreadedConnectionPool(\n'
                '            minconn, maxconn, dsn\n'
                '        )\n\n'
                '    @contextmanager\n'
                '    def cursor(self):\n'
                '        conn = self._pool.getconn()\n'
                '        try:\n'
                '            with conn, conn.cursor() as cur:\n'
                '                yield cur\n'
                '        finally:\n'
                '            self._pool.putconn(conn)\n\n'
                '    def close(self):\n'
                '        self._pool.closeall()\n\n'
                '# Использование\n'
                'db = Database("postgresql://user:pass@localhost/mydb")\n\n'
                'with db.cursor() as cur:\n'
                '    cur.execute(\n'
                '        "INSERT INTO users(name, email) VALUES (%s, %s) RETURNING id",\n'
                '        ("Alice", "alice@example.com")\n'
                '    )\n'
                '    user_id = cur.fetchone()[0]\n\n'
                'with db.cursor() as cur:\n'
                '    cur.execute("SELECT * FROM users WHERE id = %s", (user_id,))\n'
                '    user = cur.fetchone()\n'
                '    print(user)\n\n'
                '# Alembic migration (migrations/versions/001_create_users.py)\n'
                '"""\n'
                'def upgrade():\n'
                '    op.create_table("users",\n'
                '        sa.Column("id", sa.Integer, primary_key=True),\n'
                '        sa.Column("name", sa.String(100), nullable=False),\n'
                '        sa.Column("email", sa.String(255), unique=True),\n'
                '        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),\n'
                '    )\n'
                '    op.create_index("ix_users_email", "users", ["email"])\n\n'
                'def downgrade():\n'
                '    op.drop_table("users")\n'
                '"""'
            ),
        },
        {
            'title': 'ORM: SQLAlchemy Core и ORM',
            'estimated_minutes': 45,
            'content': (
                '<h3>1. SQLAlchemy Core — SQL Expression Language</h3>'
                '<p>Core — низкоуровневый слой. Строишь запросы через Python-объекты, не строки. '
                '<code>select(users).where(users.c.age > 18).order_by(users.c.name)</code>. '
                'Безопасно от SQL injection. Переносимо между БД. '
                'Компилирует в диалект-специфичный SQL.</p>'
                '<h3>2. SQLAlchemy ORM — Declarative</h3>'
                '<p><code>class User(Base): __tablename__ = "users"</code>. '
                'Поля как атрибуты: <code>id = Column(Integer, primary_key=True)</code>. '
                'Relationships: <code>posts = relationship("Post", back_populates="author")</code>. '
                'Lazy loading vs eager loading (joinedload, selectinload). '
                'Session — Unit of Work: отслеживает изменения, коммитит всё вместе.</p>'
                '<h3>3. Session lifecycle</h3>'
                '<p>Создание: <code>session = Session(engine)</code> или через sessionmaker. '
                '<code>session.add(obj)</code> — добавить. '
                '<code>session.commit()</code> — зафиксировать. '
                '<code>session.rollback()</code> — отменить. '
                '<code>session.close()</code> — освободить. '
                'Скоуп: один запрос = одна сессия (web), или долгая = интерактивное приложение.</p>'
                '<h3>4. Запросы: filter, join, aggregation</h3>'
                '<p><code>session.query(User).filter(User.age > 18).all()</code>. '
                '<code>.filter_by(name="Alice")</code> — по равенству. '
                '<code>.join(Post).filter(Post.published == True)</code>. '
                '<code>session.query(func.count(User.id)).scalar()</code>. '
                '<code>session.query(User.name, func.count(Post.id)).join(Post).group_by(User.name).all()</code>.</p>'
                '<h3>5. SQLAlchemy 2.0: новый стиль</h3>'
                '<p>select() вместо session.query(). '
                '<code>session.execute(select(User).where(User.age > 18)).scalars().all()</code>. '
                'Mapped[] аннотации для типизированных моделей. '
                '<code>class User(Base): id: Mapped[int] = mapped_column(primary_key=True)</code>. '
                'AsyncSession для async приложений (FastAPI, aiohttp).</p>'
            ),
            'code_example': (
                'from sqlalchemy import create_engine, Column, Integer, String, ForeignKey, func, select\n'
                'from sqlalchemy.orm import DeclarativeBase, relationship, Session, Mapped, mapped_column\n\n'
                'engine = create_engine("sqlite:///:memory:", echo=False)\n\n'
                'class Base(DeclarativeBase): pass\n\n'
                'class Author(Base):\n'
                '    __tablename__ = "authors"\n'
                '    id: Mapped[int] = mapped_column(primary_key=True)\n'
                '    name: Mapped[str] = mapped_column(String(100))\n'
                '    books: Mapped[list["Book"]] = relationship(back_populates="author")\n\n'
                'class Book(Base):\n'
                '    __tablename__ = "books"\n'
                '    id: Mapped[int] = mapped_column(primary_key=True)\n'
                '    title: Mapped[str] = mapped_column(String(200))\n'
                '    year: Mapped[int]\n'
                '    author_id: Mapped[int] = mapped_column(ForeignKey("authors.id"))\n'
                '    author: Mapped[Author] = relationship(back_populates="books")\n\n'
                'Base.metadata.create_all(engine)\n\n'
                'with Session(engine) as session:\n'
                '    # Добавить данные\n'
                '    alice = Author(name="Alice Smith")\n'
                '    alice.books = [\n'
                '        Book(title="Python Basics", year=2020),\n'
                '        Book(title="Advanced Python", year=2022),\n'
                '    ]\n'
                '    session.add(alice)\n'
                '    session.commit()\n\n'
                '    # SQLAlchemy 2.0 стиль\n'
                '    stmt = (select(Author)\n'
                '            .where(Author.name.like("%Smith%")))\n'
                '    authors = session.execute(stmt).scalars().all()\n\n'
                '    # Агрегация\n'
                '    result = session.execute(\n'
                '        select(Author.name, func.count(Book.id).label("book_count"))\n'
                '        .join(Book)\n'
                '        .group_by(Author.name)\n'
                '        .order_by(func.count(Book.id).desc())\n'
                '    ).all()\n'
                '    for name, count in result:\n'
                '        print(f"{name}: {count} books")'
            ),
        },
    ],
}


class Command(BaseCommand):
    help = 'Expand OAIP modules 31-45'

    def handle(self, *args, **options):
        try:
            subj = Subject.objects.get(slug='oaip')
        except Subject.DoesNotExist:
            try:
                subj = Subject.objects.get(title__icontains='ОАИП')
            except Subject.DoesNotExist:
                self.stdout.write('[ERROR] OAIP subject not found')
                return

        created = 0
        for module_title, lessons in LESSONS.items():
            try:
                module = subj.modules.get(title=module_title)
            except TheoryModule.DoesNotExist:
                self.stdout.write(f'[SKIP] {module_title}')
                continue

            max_order = module.lessons.order_by('-order').values_list('order', flat=True).first() or 0
            for i, ld in enumerate(lessons):
                obj, is_new = TheoryLesson.objects.get_or_create(
                    module=module,
                    title=ld['title'],
                    defaults={
                        'content': ld['content'],
                        'code_example': ld.get('code_example', ''),
                        'order': max_order + i + 1,
                        'estimated_minutes': ld.get('estimated_minutes', 40),
                    }
                )
                if is_new:
                    created += 1
                    self.stdout.write(f'  [+] {module_title}: {ld["title"]}')

        self.stdout.write(f'\nDone. Created: {created}')
