# Generated by Django 5.2.6 on 2025-09-09 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('theory_text', models.TextField(blank=True, verbose_name='Теоретический материал')),
                ('input_example', models.TextField(blank=True, verbose_name='Пример входных данных')),
                ('output_example', models.TextField(blank=True, verbose_name='Пример выходных данных')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна для сдачи')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Практическая работа',
                'verbose_name_plural': 'Практические работы',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_file', models.FileField(upload_to='solutions/%Y/%m/%d/', verbose_name='Файл с решением')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('checking', 'Проверяется'), ('correct', 'Верно'), ('incorrect', 'Есть ошибки')], default='submitted', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.practicalwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
    ]
