# Generated by Django 5.2.6 on 2025-09-10 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicalwork',
            options={'ordering': ['order'], 'verbose_name': 'Практическая работа', 'verbose_name_plural': 'Практические работы'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Решение', 'verbose_name_plural': 'Решения'},
        ),
        migrations.AddField(
            model_name='practicalwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicalwork',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок сдачи'),
        ),
        migrations.AddField(
            model_name='practicalwork',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='practicalwork',
            name='max_score',
            field=models.IntegerField(default=10, verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='practicalwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='execution_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AddField(
            model_name='solution',
            name='memory_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='Использование памяти'),
        ),
        migrations.AddField(
            model_name='solution',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='solution',
            name='test_results',
            field=models.JSONField(default=dict, verbose_name='Результаты тестов'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('checking', 'Проверяется'), ('correct', 'Верно'), ('incorrect', 'Есть ошибки'), ('partially_correct', 'Частично верно')], default='submitted', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_works', models.IntegerField(default=0, verbose_name='Всего работ')),
                ('completed_works', models.IntegerField(default=0, verbose_name='Выполнено работ')),
                ('total_score', models.IntegerField(default=0, verbose_name='Общий балл')),
                ('average_score', models.FloatField(default=0, verbose_name='Средний балл')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Дней подряд')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
            },
        ),
    ]
