# Generated by Django 5.2.6 on 2025-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_practicalwork_options_alter_solution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_xp',
            field=models.IntegerField(default=0, verbose_name='Текущий опыт'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='next_level_xp',
            field=models.IntegerField(default=100, verbose_name='Опыт до след. уровня'),
        ),
    ]
