# Generated by Django 5.2.6 on 2025-09-19 04:41

import django.utils.timezone
import works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_userprogress_current_xp_userprogress_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='compile_log',
            field=models.TextField(blank=True, verbose_name='Лог компиляции'),
        ),
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AddField(
            model_name='solution',
            name='run_log',
            field=models.TextField(blank=True, verbose_name='Лог выполнения'),
        ),
        migrations.AddField(
            model_name='solution',
            name='verdict_text',
            field=models.TextField(blank=True, verbose_name='Вердикт'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='code_file',
            field=models.FileField(upload_to=works.models.solution_upload_path, verbose_name='Файл с решением'),
        ),
    ]
