# Generated by Django 5.2.6 on 2025-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_solution_compile_log_solution_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalwork',
            name='topic',
            field=models.CharField(choices=[('search', 'Алгоритмы поиска'), ('sorting', 'Сортировка'), ('data_structures', 'Структуры данных'), ('recursion', 'Рекурсия'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тема'),
        ),
    ]
