# Generated by Django 5.2.6 on 2025-09-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_practicalwork_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Ключ сессии')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Длительность в секундах')),
                ('page_views', models.IntegerField(default=0, verbose_name='Количество просмотров страниц')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL страницы')),
                ('page_title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('view_time', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Время на странице (сек)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.usersession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'ordering': ['-view_time'],
            },
        ),
    ]
