# Generated by Django 5.2.6 on 2025-09-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_usersession_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('syntax', 'Синтаксическая проверка'), ('logic', 'Логическая проверка'), ('efficiency', 'Проверка эффективности'), ('style', 'Проверка стиля кода'), ('comprehensive', 'Комплексная проверка')], max_length=50, verbose_name='Тип проверки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('score', models.IntegerField(default=0, verbose_name='Балл (0-100)')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь')),
                ('suggestions', models.TextField(blank=True, verbose_name='Предложения по улучшению')),
                ('errors', models.TextField(blank=True, verbose_name='Найденные ошибки')),
                ('warnings', models.TextField(blank=True, verbose_name='Предупреждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.solution', verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'Проверка кода',
                'verbose_name_plural': 'Проверки кода',
                'ordering': ['-created_at'],
            },
        ),
    ]
