# Generated by Django 5.2.6 on 2025-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_codecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalwork',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript')], default='python', max_length=20, verbose_name='Язык программирования'),
        ),
    ]
