# Generated by Django 5.2.6 on 2026-05-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_module_requires_quiz_solution_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='⭐', max_length=4, verbose_name='Иконка')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='Награда XP')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'verbose_name': 'Просмотр страницы', 'verbose_name_plural': 'Просмотры страниц'},
        ),
        migrations.AlterModelOptions(
            name='teachercomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий преподавателя', 'verbose_name_plural': 'Комментарии преподавателя'},
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='check_type',
            field=models.CharField(default='comprehensive', max_length=50, verbose_name='Тип проверки'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='errors',
            field=models.JSONField(default=list, verbose_name='Найденные ошибки'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('in_progress', 'Проверяется'), ('completed', 'Проверка завершена'), ('failed', 'Ошибка проверки')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='suggestions',
            field=models.JSONField(default=list, verbose_name='Предложения по улучшению'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='warnings',
            field=models.JSONField(default=list, verbose_name='Предупреждения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_snippet',
            field=models.TextField(blank=True, verbose_name='Код (если нужен)'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('checking', 'Проверяется'), ('correct', 'Верно'), ('incorrect', 'Есть ошибки'), ('partially_correct', 'Частично верно')], default='submitted', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='teachercomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WorkHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('title', models.CharField(default='Подсказка', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст подсказки')),
                ('xp_cost', models.PositiveIntegerField(default=5, verbose_name='Стоимость (XP)')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='works.practicalwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('new_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Новый дедлайн')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Запрошено')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extensions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.practicalwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Запрос продления дедлайна',
                'verbose_name_plural': 'Запросы продления дедлайна',
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'work')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserHintUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыто')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.workhint', verbose_name='Подсказка')),
            ],
            options={
                'verbose_name': 'Открытая подсказка',
                'verbose_name_plural': 'Открытые подсказки',
                'unique_together': {('user', 'hint')},
            },
        ),
    ]
