# Generated by Django 5.2.6 on 2026-05-18 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0014_achievement_alter_notification_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=20, unique=True, verbose_name="Slug"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-book", max_length=50, verbose_name="Иконка"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#667eea", max_length=20, verbose_name="Цвет"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Конспект"),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="practicalwork",
            name="tinkercad_url",
            field=models.URLField(blank=True, verbose_name="Ссылка Tinkercad (для МК)"),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Скрыть с даты"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="works.subject",
                        verbose_name="Предмет (пусто = все)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="practicalwork",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="works",
                to="works.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="theorymodule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="works.subject",
                verbose_name="Предмет",
            ),
        ),
    ]
