# Generated by Django 5.2.6 on 2026-05-18 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0015_subject_lessonprogress_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CircuitSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("circuit_json", models.TextField(verbose_name="JSON схемы")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Сдано"),
                            ("reviewed", "Проверено"),
                            ("correct", "Зачтено"),
                            ("incorrect", "Не зачтено"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="Балл")),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий студента"),
                ),
                (
                    "teacher_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий преподавателя"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuit_solutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuit_solutions",
                        to="works.practicalwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Решение схемы",
                "verbose_name_plural": "Решения схем",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CircuitDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "circuit_json",
                    models.TextField(default="{}", verbose_name="JSON схемы"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuit_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuit_drafts",
                        to="works.practicalwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Черновик схемы",
                "verbose_name_plural": "Черновики схем",
                "unique_together": {("student", "work")},
            },
        ),
    ]
