# Generated by Django 5.2.6 on 2026-06-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_userprogress_must_change_password_subjectaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalwork',
            name='theory_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_works', to='works.theorymodule', verbose_name='Связанный модуль теории'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Лёгкий'), (2, 'Средний'), (3, 'Сложный')], default=2, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки кода'),
        ),
    ]
