# Generated by Django 5.2.6 on 2026-09-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_student_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит времени (мин)'),
        ),
    ]
