# Generated by Django 5.2.6 on 2026-09-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0020_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalwork',
            name='wokwi_url',
            field=models.URLField(blank=True, verbose_name='Ссылка Wokwi проекта (для МК)'),
        ),
    ]
