# Generated by Django 5.2.6 on 2026-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0021_practicalwork_wokwi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Время прохождения (сек)'),
        ),
    ]
