# Generated by Django 5.2.6 on 2026-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0022_quiz_attempt_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='focus_loss_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Уходы со вкладки'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='suspicious',
            field=models.BooleanField(default=False, verbose_name='Подозрительная попытка'),
        ),
    ]
