# Generated by Django 5.2.6 on 2026-09-21 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0023_quiz_attempt_suspicious'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема курсовой работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание / задание')),
                ('status', models.CharField(choices=[('assigned', 'Назначена'), ('in_progress', 'Выполняется'), ('submitted', 'Сдана на проверку'), ('defended', 'Защищена'), ('rejected', 'На доработку')], default='assigned', max_length=20, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('teacher_note', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка (1-5)')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course_works', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_works', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Курсовая работа',
                'verbose_name_plural': 'Курсовые работы',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
