# Generated by Django 5.2.6 on 2026-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0024_coursework'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='method_guide',
            field=models.FileField(blank=True, null=True, upload_to='coursework_guides/', verbose_name='Методичка (PDF)'),
        ),
    ]
