# Generated by Django 5.2.6 on 2026-09-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0025_subject_method_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='example_cw_file',
            field=models.FileField(blank=True, null=True, upload_to='coursework_guides/', verbose_name='Пример курсовой работы'),
        ),
    ]
