# Generated by Django 5.2.6 on 2026-09-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0026_subject_example_cw'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='similarity_matches',
            field=models.JSONField(blank=True, default=list, verbose_name='Совпадения'),
        ),
        migrations.AddField(
            model_name='solution',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс. схожесть (%)'),
        ),
    ]
