# Generated by Django 5.2.6 on 2026-09-28 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0027_similarity_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PyGridScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_completed', models.PositiveIntegerField(default=0, verbose_name='Раундов пройдено')),
                ('stars_total', models.PositiveIntegerField(default=0, verbose_name='Всего звёзд')),
                ('best_steps', models.PositiveIntegerField(default=0, verbose_name='Лучший суммарный шаг')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pygrid_score', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Результат PyGrid',
                'verbose_name_plural': 'Результаты PyGrid',
                'ordering': ['-rounds_completed', '-stars_total', 'best_steps'],
            },
        ),
    ]
